# Generated by Django 3.2.10 on 2022-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_two_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor',
        ),
    ]
