# Generated by Django 3.2.10 on 2022-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_two_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
