# Generated by Django 3.2.10 on 2022-05-02 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
