# Generated by Django 3.2.10 on 2022-05-04 15:02

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='csc',
            field=models.CharField(default=cards.models.set_csc, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
