# Generated by Django 3.2.10 on 2022-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20220504_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
