# Generated by Django 3.2.10 on 2022-05-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20220506_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_deleted',
        ),
    ]
